---
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Backend (poetry)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    reviewers:
      - "pozsa"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "pozsa"

  # Maintain dependencies for Frontend (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    reviewers:
      - "pozsa"
