version: "3.8"

services:
  keycloak:
    container_name: keycloak-aof
    image: quay.io/keycloak/keycloak:15.1.0
    volumes:
      - ./keycloak:/tmp/io
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/io/dev-realm.json
      - KEYCLOAK_STATISTICS=all # enables the health endpoint under 9990
    ports:
      - 8080:8080
      - 9990:9990
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9990/health || exit 1"
        ]
      start_period: 1m30s # realm import seems to take some time

  app:
    container_name: app-aof
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/aof
    environment:
      - VERSION=dev
      - RELEASEID=dev
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8000/health || exit 1"
        ]
