version: "3.8"

services:
  app:
    container_name: aof
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/aof
    command: /bin/sh -c "while sleep 1000; do :; done" # infinite loop
