---
name: Build and Push Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/build-and-push-backend.yaml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    defaults:
      run:
        # Step into backend
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . \
          --build-arg VERSION=${{ github.sha }} \
          --build-arg RELEASE_ID=${{ github.sha }} \
          -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alphafold:stage
          docker push {{ secrets.REGISTRY_LOGIN_SERVER }}/alphafold:stage
