---
name: Lint Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/lint-backend.yaml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/lint-backend.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    defaults:
      run:
        # Step into backend
        working-directory: ./backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.5.1

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Ruff
        run: poetry run ruff check .

      - name: Black
        run: poetry run black . --check --diff
