---
name: Lint Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/lint-backend.yaml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/lint-backend.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    defaults:
      run:
        # Step into backend
        working-directory: ./backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.0.265
