name: Test Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "!backend/README.md"
      - ".github/workflows/test-backend.yaml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "!backend/README.md"
      - ".github/workflows/test-backend.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    container: python:3.9
    defaults:
      run:
        # Step into backend
        working-directory: ./backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Run tests
        env:
          VERSION: test
          RELEASEID: test
        run: |
          python -m pytest --cov=app --cov-report=xml

      - name: Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
        uses: codecov/codecov-action@v2
        with:
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: backend # optional
